
cloud:
    aws:
        stack:
            auto: false
            enabled: false
        credentials:
            access-key: localstackAccessKeyId
            secret-key: localstackSecretAccessKey
        region:
            static: eu-west-1
