name: java-spring-aws-s3-plugin
description: This plugin enables the ability to manage files and objects in Amazon S3 Storage in your Java Spring Boot Application
display-name: java-spring-aws-s3-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
  - maven
  - application.yaml
about: docs/pt-br/doc.md
usage: docs/pt-br/doc.md
use-case: docs/pt-br/doc.md
implementation: docs/pt-br/doc.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
computed-inputs:
  directory: "{{directory_path | replace('.','/')}}"
  directory_test: "{{directory_test_path | replace('.','/')}}"

hooks:
  ##
  # Edit pom.xml add multiples dependencies with Spring AWS core, Test Containers and Spring Cloud Dependency Management
  ##
  - type: edit
    path: pom.xml
    trigger: after-render
    changes:
      - search:
          string: "</dependencies>"
          insert-before:
            snippet: snippets/snippet-pom.xml
          when:
            not-exists-snippet: snippets/snippet-pom.xml
      - search:
          string: "</dependencies>"
          insert-after:
            snippet: snippets/snippet-pom-dependencymanagement.xml
          when:
            not-exists: "spring-cloud-aws-dependencies"
      - search:
          string: "</dependencies>"
          insert-before:
            snippet: snippets/snippet-pom-dependecies-test-containers-localstack.xml
          when:
            not-exists-snippet: snippets/snippet-pom-dependecies-test-containers-localstack.xml

  ##
  # Edit application.yaml
  ##
  - type: edit
    path: src/main/resources/application.yaml
    trigger: after-render
    changes:
      - insert:
          line: -1 
          snippet: snippets/snippet-application.yaml
          when:
            not-exists-snippet: snippets/snippet-application.yaml
      - search:
          string: "aws:"
          insert-after:
            snippet: snippets/snippet-s3-application.yaml
          when:
            not-exists: "s3:"
      - insert:
          line: -1
          value: "\nlogging.level.com.amazonaws.services.s3: debug"
          when:
            not-exists: "logging.level.com.amazonaws.services.s3: debug"
      - insert:
          line: -1
          value: "\nlogging.level.com.amazonaws.util.EC2MetadataUtils: error"
          when:
            not-exists: "logging.level.com.amazonaws.util.EC2MetadataUtils: error"
  ##
  # Create or edit docker-compose.yaml
  ##
  - type: render-templates
    trigger: after-render
    path: snippets/docker-localstack

  ##
  # Create path directory samples
  ##
  - type: run-script
    trigger: before-input
    script: snippets/open-pom.py
